version: '3.8'
networks:
  frontend:
    external: true
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - '3000:3000'
    networks:
      - frontend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://192.168.10.156:3000/api/
      BACK_PUBLIC_API_URL: http://192.168.10.156:8384/
      REDIS_URL: 192.168.10.156
      TRANSFER_DOMAIN: http://192.168.10.156:3001
