import Providers from "@/store/provider";
import { Montserrat } from "@next/font/google";
import Carrito from "./carrito/Carrito"
const fuente = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={fuente.className}>
          <Carrito/>
          <div>{children}</div>
        </body>
      </Providers>
    </html>
  );
}
