version: '3.8'
networks:
  frontend:
    external: true
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: yarn start
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
    networks:
      - frontend