import Head from 'next/head'
import dynamic from 'next/dynamic'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/footer'
import { Fragment, lazy, Suspense } from 'react'

import { useContext } from "react";
import { useRouter } from "next/router";
import MyContextProvider, { Message_data } from '@/context/MyContextProvider'
import Link from 'next/link';
import { Url } from 'url'
import { Layout } from '@/components/layout/Layout'

const inter = Inter({ subsets: ['latin'] })


//

// @ts-ignore  
const TransferReact = dynamic(() => import('remote2/TransferReact'), {
  ssr: false,
});


/*
const NextjsRemoteComponent = dynamic(() => import('remote/nextjs-remote-component'), {
  ssr: false,
  loading: ({ error }) => {
    console.log("error cargando DemoApp3C",error);
    if (error) {
      return <Fragment>Error</Fragment>;
    }
    return <Fragment>Loading</Fragment>;
  }
});
*/
/*
const Header = (import('mf_demo/Demo')).default;
*/



export default function Home() { 
  const router = useRouter();
   
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
      <Layout title='Home - HDRM PYT'>
             
        <main className={styles.main}>
      
        <Link href="TransferReact" onClick={() => router.push('TransferReact')}>
          GO TO TRANSFER          
        </Link>
        
        <div className={styles.description}>
          <p>
            HOST Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          
        </div>

       
        
        
      </main>
      
      </Layout>
    </>
  )
}


