export const propias = [
  { value: "0123***3245", label: "Gastos personales 0123***3245" },
  { value: "0123***4087", label: "Ahorros varios 0123***4087" },
  { value: "0123***3580", label: "Cuenta familiar 0123***3580" },
];

export const propias2 = {
  messageId:
    "eC5mYWJhOWFybHVwLlQwUlIueXd5endGeHggd0Z3eHp6LkF5WFJFVVV4QUNLSEdMVkFPQ1FF",
  responseCode: "0000",
  responseDesc: "Customer accounts obtained",
  responseBody: [
    {
      actionDebited: "A",
      numberAccount: "404406000102",
      typeAccount: "10",
      currency: "USD",
      balance: 100.0,
      status: "ACTIVA",
      descriptionAccount: "Ahorro Personal",
    },
    {
      actionDebited: "A",
      numberAccount: "411010000076",
      typeAccount: "10",
      currency: "USD",
      balance: 252.0,
      status: "ACTIVA",
      descriptionAccount: "Ahorro Personal",
    },
    {
      actionDebited: "D",
      numberAccount: "411010000181",
      typeAccount: "10",
      currency: "USD",
      balance: 253.0,
      status: "ACTIVA",
      descriptionAccount: "Ahorro Personal",
    },
    {
      actionDebited: "D",
      numberAccount: "411010000193",
      typeAccount: "10",
      currency: "USD",
      balance: 0.0,
      status: "ACTIVA",
      descriptionAccount: "Ahorro Personal",
    },
    {
      actionDebited: "C",
      numberAccount: "41101001715",
      typeAccount: "10",
      currency: "USD",
      balance: 0.0,
      status: "ACTIVA",
      descriptionAccount: "Ahorro Personal",
    },
    {
      actionDebited: "C",
      numberAccount: "411030000038",
      typeAccount: "10",
      currency: "USD",
      balance: 0.0,
      status: "ACTIVA",
      descriptionAccount: "Ahorro Personal",
    },
    {
      actionDebited: "A",
      numberAccount: "4256311111",
      typeAccount: "10",
      currency: "USD",
      balance: 0.0,
      status: "ACTIVA",
      descriptionAccount: "Ahorro Personal",
    },
    {
      actionDebited: "A",
      numberAccount: "4256319985",
      typeAccount: "10",
      currency: "USD",
      balance: 0.0,
      status: "ACTIVA",
      descriptionAccount: "Ahorro Personal",
    },
  ],
};
